Repository nickschot/ember-mobile-menu, pull requests merged in 2020-12, with the labels that each got.

#104 switch to github CI
  .github/workflows/ci.yaml
  .travis.yml
Labels: internal

#102 upgrade to ember-cli 3.22 & update dependencies
  config/ember-try.js
  package.json
  tests/dummy/config/ember-cli-update.json
  yarn.lock
Labels: enhancement

#100 remove old service re-export (fixes embroider build)
  app/services/mobile-menu.js
Labels: bug

#106 Github CI: allow canary tests to fail, remove job dependencies
  .github/workflows/ci.yaml
Labels: internal

#105 properly cleanup body-scroll-lock when the tray component is destroyed
  addon/components/mobile-menu/tray.hbs
  tests/integration/components/mobile-menu/tray-test.js
Labels: bug

#107 add ember-data dev dependency
  package.json
  yarn.lock
Labels: internal

#108 manually add application wrapper to dummy app as addon docs styles expect it
  tests/dummy/app/styles/app.scss
  tests/dummy/app/templates/application.hbs
Labels: documentation
